"""The libfuzzer_native.cc.j2 template renders a syntactically-valid C++
LLVMFuzzerTestOneInput harness given an EntryPoint context.

Per Asemarefactor.md lines 215-225, the canonical libwebp shape is:

    #include <webp/decode.h>
    extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
        int w, h;
        uint8_t* rgb = WebPDecodeRGB(data, size, &w, &h);
        if (rgb) WebPFree(rgb);
        return 0;
    }

This test exercises the template renderer directly with a synthetic context
and checks the rendered output for the required structural elements.
"""

from __future__ import annotations

from aegisgraph.harnessgen.templates import render_libfuzzer_native


def _webp_context() -> dict:
    return {
        "harness_id": "WebPDecodeRGB",
        "header": "webp/decode.h",
        "entry_function": "WebPDecodeRGB",
        "free_function": "WebPFree",
        # signature info from the extractor
        "entry_return_type": "uint8_t*",
        "entry_data_param": "data",
        "entry_size_param": "size",
        "out_dims": ["w", "h"],
    }


def test_template_includes_required_header() -> None:
    rendered = render_libfuzzer_native(_webp_context())
    assert "#include <webp/decode.h>" in rendered


def test_template_emits_llvm_fuzzer_entrypoint() -> None:
    rendered = render_libfuzzer_native(_webp_context())
    assert 'extern "C"' in rendered
    assert "LLVMFuzzerTestOneInput" in rendered
    # Signature must match libFuzzer's exact prototype.
    assert "const uint8_t* data" in rendered
    assert "size_t size" in rendered


def test_template_calls_entry_function() -> None:
    rendered = render_libfuzzer_native(_webp_context())
    # The body invokes WebPDecodeRGB with data + size + &w + &h.
    assert "WebPDecodeRGB(data, size" in rendered


def test_template_frees_on_success() -> None:
    rendered = render_libfuzzer_native(_webp_context())
    # The Asemarefactor canonical template guards WebPFree behind a non-null
    # check on the decoded buffer.
    assert "WebPFree" in rendered
    # Both shapes are acceptable: `if (rgb)` or `if (rgb != nullptr)`.
    body = rendered.lower()
    assert "if (rgb" in body


def test_template_returns_zero() -> None:
    rendered = render_libfuzzer_native(_webp_context())
    assert "return 0;" in rendered


def test_template_has_generator_comment() -> None:
    """Generated harnesses must mark themselves so a human reviewer can
    tell at a glance that the file is regenerable, not hand-written."""
    rendered = render_libfuzzer_native(_webp_context())
    lowered = rendered.lower()
    assert "auto-generated" in lowered or "generated by" in lowered
    assert "harnessgen" in lowered


def test_template_no_raw_bytes_leakage() -> None:
    """Defense-in-depth: a harness template must never include literals
    that look like crash-payload byte data. The template is parameterized
    over function names, not over bytes."""
    rendered = render_libfuzzer_native(_webp_context())
    forbidden = ("bytes_b64", "payload_b64", "raw_bytes", "raw_witness")
    for token in forbidden:
        assert token not in rendered, f"template leaked forbidden token: {token}"
