"""The jazzer_jvm.java.j2 template renders a syntactically-valid Java
fuzzerTestOneInput entrypoint given a JvmEntryPoint context.

Per Asemarefactor.md lines 168-186, the canonical Signal LinkPreviewUtil
shape is:

    package org.aegisgraph.fuzz;

    import com.code_intelligence.jazzer.api.FuzzedDataProvider;
    import org.thoughtcrime.securesms.linkpreview.LinkPreviewUtil;

    public class LinkPreviewUtilFuzzer {
        public static void fuzzerTestOneInput(FuzzedDataProvider data) {
            try {
                String input = data.consumeRemainingAsString();
                LinkPreviewUtil.findValidPreviewUrls(input);
            } catch (IllegalArgumentException | StringIndexOutOfBoundsException e) {
                // expected; ignore
            }
        }
    }

This test exercises the template renderer directly with a synthetic
context and checks the rendered output for the required structural
elements verbatim against the spec.
"""

from __future__ import annotations

from aegisgraph.harnessgen.templates import render_jazzer_jvm


def _signal_link_preview_context() -> dict:
    return {
        "harness_id": "LinkPreviewUtilFuzzer",
        "package": "org.aegisgraph.fuzz",
        "target_import": "org.thoughtcrime.securesms.linkpreview.LinkPreviewUtil",
        "fuzzer_class_name": "LinkPreviewUtilFuzzer",
        "target_call": "LinkPreviewUtil.findValidPreviewUrls(input)",
        "expected_exceptions": [
            "IllegalArgumentException",
            "StringIndexOutOfBoundsException",
        ],
    }


def test_template_emits_package_declaration() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert "package org.aegisgraph.fuzz;" in rendered


def test_template_imports_fuzzed_data_provider() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert "import com.code_intelligence.jazzer.api.FuzzedDataProvider;" in rendered


def test_template_imports_target() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert (
        "import org.thoughtcrime.securesms.linkpreview.LinkPreviewUtil;"
        in rendered
    )


def test_template_declares_public_fuzzer_class() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert "public class LinkPreviewUtilFuzzer {" in rendered


def test_template_emits_fuzzer_test_one_input() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert (
        "public static void fuzzerTestOneInput(FuzzedDataProvider data) {"
        in rendered
    )


def test_template_consumes_remaining_as_string() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert "String input = data.consumeRemainingAsString();" in rendered


def test_template_calls_target() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    assert "LinkPreviewUtil.findValidPreviewUrls(input);" in rendered


def test_template_catches_expected_exceptions() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    # The try/catch handles IllegalArgumentException + StringIndexOutOfBoundsException
    assert "try {" in rendered
    assert (
        "catch (IllegalArgumentException | StringIndexOutOfBoundsException e)"
        in rendered
    )
    assert "// expected; ignore" in rendered


def test_template_has_generator_comment() -> None:
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    lowered = rendered.lower()
    assert "auto-generated" in lowered or "generated by" in lowered
    assert "harnessgen" in lowered


def test_template_no_raw_bytes_leakage() -> None:
    """Defense-in-depth: a JVM harness template must never include literals
    that look like crash-payload byte data. The template is parameterized
    over identifiers, not over bytes."""
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    forbidden = ("bytes_b64", "payload_b64", "raw_bytes", "raw_witness")
    for token in forbidden:
        assert token not in rendered, f"template leaked forbidden token: {token}"


def test_template_renders_with_different_exception_set() -> None:
    """Variation: a different target wants ArrayIndexOutOfBoundsException +
    NullPointerException — the template must accept arbitrary lists."""
    ctx = _signal_link_preview_context()
    ctx["expected_exceptions"] = [
        "ArrayIndexOutOfBoundsException",
        "NullPointerException",
    ]
    rendered = render_jazzer_jvm(ctx)
    assert (
        "catch (ArrayIndexOutOfBoundsException | NullPointerException e)"
        in rendered
    )


def test_template_matches_asemarefactor_spec_verbatim_when_canonical_inputs() -> None:
    """End-to-end: when fed the exact canonical inputs from Asemarefactor.md
    lines 168-186, the rendered output (ignoring the leading generator
    comment) must contain the full canonical class declaration verbatim."""
    rendered = render_jazzer_jvm(_signal_link_preview_context())
    # Spec lines 171-185 — every key line must appear verbatim.
    must_contain = [
        "package org.aegisgraph.fuzz;",
        "import com.code_intelligence.jazzer.api.FuzzedDataProvider;",
        "import org.thoughtcrime.securesms.linkpreview.LinkPreviewUtil;",
        "public class LinkPreviewUtilFuzzer {",
        "public static void fuzzerTestOneInput(FuzzedDataProvider data) {",
        "try {",
        "String input = data.consumeRemainingAsString();",
        "LinkPreviewUtil.findValidPreviewUrls(input);",
        "} catch (IllegalArgumentException | StringIndexOutOfBoundsException e) {",
        "// expected; ignore",
    ]
    for needle in must_contain:
        assert needle in rendered, f"missing spec line: {needle!r}"
