"""The build/jvm.gradle.j2 template renders a Gradle build stub that pulls
ONLY the parser module + minimal deps (Jazzer + the host Signal Android
module containing the target class).

Per Asemarefactor.md line 188:

  "Generate build files (Gradle stub that pulls only the parser module
  and its minimal deps, not the full Signal app)."

The template:
  * uses placeholder version numbers (real pinning happens at M5.1.b)
  * documents the placeholders in a comment block
  * declares the Jazzer dependency
  * declares the target's parser module
  * does NOT pull the full Signal-Android Gradle root project

Tests check structure only; they do NOT invoke gradle.
"""

from __future__ import annotations

from aegisgraph.harnessgen.templates import render_jvm_gradle


def _signal_link_preview_context() -> dict:
    return {
        "harness_id": "LinkPreviewUtilFuzzer",
        "target_module": "org.thoughtcrime.securesms:link-preview-parser",
        "target_module_version": "PLACEHOLDER",
        "jazzer_version": "0.22.1",
        "java_version": "17",
        "fuzzer_main_class": "org.aegisgraph.fuzz.LinkPreviewUtilFuzzer",
        "harness_source": "LinkPreviewUtilFuzzer.java",
    }


def test_gradle_has_plugin_block() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    # A Java + application plugin combo is the canonical Jazzer harness shape.
    assert "plugins {" in rendered
    assert "id 'java'" in rendered or "java" in rendered


def test_gradle_declares_jazzer_dependency() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    # The Jazzer API + driver pulled from CodeIntelligence Maven Central.
    assert "com.code-intelligence:jazzer-api" in rendered
    assert "0.22.1" in rendered  # placeholder version surfaced through


def test_gradle_declares_target_parser_module() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    # Only the parser module is pulled — not the full Signal Android app.
    assert "org.thoughtcrime.securesms:link-preview-parser" in rendered


def test_gradle_documents_placeholder_versions() -> None:
    """Placeholders are intentional; the file must say so in a top-of-file
    comment block so a reviewer can tell this is a stub awaiting M5.1.b."""
    rendered = render_jvm_gradle(_signal_link_preview_context())
    lowered = rendered.lower()
    assert "placeholder" in lowered or "to be pinned" in lowered


def test_gradle_does_not_pull_full_signal_app() -> None:
    """Defense-in-depth: the Gradle stub must NOT pull the full Signal
    Android app (Signal-Android/app), only the parser module. This keeps
    the harness build fast + the dep surface tiny."""
    rendered = render_jvm_gradle(_signal_link_preview_context())
    lowered = rendered.lower()
    forbidden_substrings = (
        "signal-android:app",
        "signal-android/app",
    )
    for token in forbidden_substrings:
        assert token not in lowered, f"gradle pulls full app via {token}"


def test_gradle_no_live_target_probing() -> None:
    """The Gradle file must NOT contain commands that download live target
    binaries or probe external services. This is a build recipe for a
    sandboxed harness only."""
    rendered = render_jvm_gradle(_signal_link_preview_context())
    lowered = rendered.lower()
    forbidden = ("nmap", "masscan", "curl http", "wget http")
    for token in forbidden:
        assert token not in lowered, f"gradle contains forbidden token: {token}"


def test_gradle_has_generator_comment() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    lowered = rendered.lower()
    assert "auto-generated" in lowered or "generated by" in lowered
    assert "harnessgen" in lowered


def test_gradle_declares_java_version() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    # Signal Android targets JDK 17.
    assert "17" in rendered


def test_gradle_references_fuzzer_main_class() -> None:
    rendered = render_jvm_gradle(_signal_link_preview_context())
    # The application plugin needs the FQN of the fuzzer main class.
    assert "org.aegisgraph.fuzz.LinkPreviewUtilFuzzer" in rendered
