"""The cargo_fuzz.rs.j2 template renders a syntactically-valid Rust
cargo-fuzz target given a RustEntryPoint-shaped context.

Per Asemarefactor.md lines 230-238, the canonical matrix-rust-sdk
MessageType shape is:

    #![no_main]
    use libfuzzer_sys::fuzz_target;
    use matrix_sdk::ruma::events::room::message::MessageType;

    fuzz_target!(|data: &[u8]| {
        let _ = serde_json::from_slice::<MessageType>(data);
    });

This test exercises the template renderer directly with a synthetic
context and checks the rendered output for the required structural
elements verbatim against the spec.
"""

from __future__ import annotations

from aegisgraph.harnessgen.templates import render_cargo_fuzz


def _message_type_context() -> dict:
    return {
        "harness_id": "matrix_rust_sdk_messagetype",
        "target_crate": "matrix_sdk",
        "target_use_path": "ruma::events::room::message::MessageType",
        "parse_call": "serde_json::from_slice::<MessageType>(data)",
    }


def test_template_emits_no_main_attr() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    assert "#![no_main]" in rendered


def test_template_imports_libfuzzer_fuzz_target() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    assert "use libfuzzer_sys::fuzz_target;" in rendered


def test_template_imports_target_use_path() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    # `use matrix_sdk::ruma::events::room::message::MessageType;`
    assert (
        "use matrix_sdk::ruma::events::room::message::MessageType;"
        in rendered
    )


def test_template_declares_fuzz_target_with_byte_slice() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    # libfuzzer-sys-style closure header.
    assert "fuzz_target!(|data: &[u8]| {" in rendered


def test_template_calls_parse_call() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    assert "let _ = serde_json::from_slice::<MessageType>(data);" in rendered


def test_template_closes_fuzz_target_block() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    # The macro form is `fuzz_target!(... { ... });` so the closer is `});`.
    assert "});" in rendered


def test_template_has_generator_comment() -> None:
    rendered = render_cargo_fuzz(_message_type_context())
    lowered = rendered.lower()
    assert "auto-generated" in lowered or "generated by" in lowered
    assert "harnessgen" in lowered


def test_template_no_raw_bytes_leakage() -> None:
    """Defense-in-depth: a harness template must never include literals
    that look like crash-payload byte data. The template is parameterized
    over identifiers, not over bytes."""
    rendered = render_cargo_fuzz(_message_type_context())
    forbidden = ("bytes_b64", "payload_b64", "raw_bytes", "raw_witness")
    for token in forbidden:
        assert token not in rendered, f"template leaked forbidden token: {token}"


def test_template_renders_with_different_target() -> None:
    """Variation: a different target wants serde_cbor::from_slice on a
    different type — the template must accept arbitrary parse_call inputs."""
    ctx = {
        "harness_id": "another_rust_target",
        "target_crate": "other_crate",
        "target_use_path": "submod::SomeType",
        "parse_call": "serde_cbor::from_slice::<SomeType>(data)",
    }
    rendered = render_cargo_fuzz(ctx)
    assert "use other_crate::submod::SomeType;" in rendered
    assert "let _ = serde_cbor::from_slice::<SomeType>(data);" in rendered


def test_template_matches_asemarefactor_spec_verbatim_when_canonical_inputs() -> None:
    """End-to-end: when fed the exact canonical inputs from Asemarefactor.md
    lines 230-238, the rendered output (ignoring the leading generator
    comment) must contain every spec line verbatim."""
    rendered = render_cargo_fuzz(_message_type_context())
    # Spec lines 231-237 — every key line must appear verbatim.
    must_contain = [
        "#![no_main]",
        "use libfuzzer_sys::fuzz_target;",
        "use matrix_sdk::ruma::events::room::message::MessageType;",
        "fuzz_target!(|data: &[u8]| {",
        "let _ = serde_json::from_slice::<MessageType>(data);",
        "});",
    ]
    for needle in must_contain:
        assert needle in rendered, f"missing spec line: {needle!r}"
