// auto-generated by aegisgraph harnessgen (LinkPreviewUtilFuzzer)
//
// Jazzer JVM entrypoint wrapping a target method. The shape is the
// canonical Asemarefactor.md Engine 2 template (lines 168-186). Build with
// the sibling build.gradle. Run only inside the HarnessGen sandbox
// (docker, self-hosted runner) -- never on a developer workstation,
// never against a live target.
//
// The crash bytes this harness produces NEVER appear in evidence records.
// They are written into reprochain/corpora-private/ and referenced by
// SHA-256 in the AG-CRASH-* record schema (schema/crash.schema.json).

package org.aegisgraph.fuzz;

import com.code_intelligence.jazzer.api.FuzzedDataProvider;
import org.thoughtcrime.securesms.linkpreview.LinkPreviewUtil;

public class LinkPreviewUtilFuzzer {
    public static void fuzzerTestOneInput(FuzzedDataProvider data) {
        try {
            String input = data.consumeRemainingAsString();
            LinkPreviewUtil.findValidPreviewUrls(input);
        } catch (IllegalArgumentException | StringIndexOutOfBoundsException e) {
            // expected; ignore
        }
    }
}
