// auto-generated by aegisgraph harnessgen (matrix_rust_sdk_messagetype)
//
// cargo-fuzz Rust entrypoint wrapping a target type. The shape is the
// canonical Asemarefactor.md Engine 2 template (lines 230-238). Build with
// the sibling Cargo.toml + nested fuzz/Cargo.toml. Run only inside the
// HarnessGen sandbox (docker, self-hosted runner) -- never on a developer
// workstation, never against a live target.
//
// The crash bytes this harness produces NEVER appear in evidence records.
// They are written into reprochain/corpora-private/ and referenced by
// SHA-256 in the AG-CRASH-* record schema (schema/crash.schema.json).

#![no_main]
use libfuzzer_sys::fuzz_target;
use matrix_sdk::ruma::events::room::message::MessageType;

fuzz_target!(|data: &[u8]| {
    let _ = serde_json::from_slice::<MessageType>(data);
});
