from __future__ import annotations

from pathlib import Path
from typing import Any

from .constants import STATIC_GENERATED_AT, TARGETS
from .evidence import evidence_ref, finalize_record, provenance
from .io import write_json
from .score import media_parser_score


def build(root: Path) -> dict[str, Any]:
    manifest = {
        "tool_output_type": "reprochain_build_manifest",
        "version": "v1.0",
        "generated_by": "aegisgraph-tier3-research",
        "generated_at": STATIC_GENERATED_AT,
        "safety_posture": "private_by_default",
        "status": "blocked_pending_commit_pin",
        "library": "libwebp",
        "required_human_decision": "Confirm exact vulnerable and fixed libwebp commit hashes before vendoring or building.",
        "safety_boundary": "No crash inputs, exploit payloads, or production-app targeting are generated by this scaffold.",
    }
    write_json(root / "reprochain" / "evidence" / "build_manifest.json", manifest)
    return manifest


def run(root: Path) -> dict[str, Any]:
    status = {
        "tool_output_type": "reprochain_run_status",
        "version": "v1.0",
        "generated_by": "aegisgraph-tier3-research",
        "generated_at": STATIC_GENERATED_AT,
        "safety_posture": "private_by_default",
        "status": "not_run_until_commit_pins_confirmed",
        "expected_future_gate": "ASAN crash on vulnerable libwebp and clean run on fixed libwebp in isolated harness only.",
        "restricted_material_policy": "Crash-inducing corpus files remain under reprochain/corpora-private and are excluded from public sanitized export.",
    }
    write_json(root / "reprochain" / "evidence" / "run_status.json", status)
    return status


def _mapping_record(target_key: str, previous_hash: str | None = None) -> dict[str, Any]:
    target = TARGETS[target_key]
    title = target["name"].replace(" ", "-").upper()
    decoder = "Glide/media decode path" if target_key == "signal" else "Coil/media decode path"
    record = {
        "id": f"AG-EV-REPROCHAIN-{title}-MAP-001",
        "version": "v1.0",
        "target": {
            "name": target["name"],
            "repo_url": target["repo_url"],
            "commit": target["commit"],
            "source_policy": "anchor-only",
        },
        "path_class": "media_decode",
        "nodes": [
            {
                "id": "entry.inbound-media",
                "node_type": "entry_point",
                "label": "Inbound media path",
                "source_anchor": f"{target['repo_url']}/tree/{target['commit']}",
                "evidence_source": "extraction output anchor",
            },
            {
                "id": "decoder.app-stack",
                "node_type": "decoder",
                "label": decoder,
                "source_anchor": f"{target['repo_url']}/tree/{target['commit']}",
                "evidence_source": "phase0 map placeholder",
            },
            {
                "id": "sink.libwebp",
                "node_type": "sink",
                "label": "libwebp CVE-2023-4863 public-information reproduction target",
                "source_anchor": "reprochain/analysis/CVE-2023-4863.md",
                "evidence_source": "public CVE writeup summary, exact commit pins pending",
            },
        ],
        "edges": [
            {"from": "entry.inbound-media", "to": "decoder.app-stack", "relationship": "may_route_to"},
            {"from": "decoder.app-stack", "to": "sink.libwebp", "relationship": "requires_decoder_indirection_validation"},
        ],
        "score_vector": media_parser_score(),
        "claim_state": "validation_tasked",
        "validation_task": {
            "id": f"VAL-REPROCHAIN-{title}",
            "command": "make reprochain-run",
            "expected_output": "isolated ASAN-only libwebp differential result after commit pins are confirmed",
            "status": "blocked",
        },
        "evidence_refs": [
            evidence_ref(
                f"REF-REPROCHAIN-{title}",
                "aegisgraph-reprochain",
                "make reprochain-map",
                f"{target['name']} media path mapping scaffold",
            )
        ],
        "recommendation_refs": [],
        "limitations": (
            "This record maps the research question and scoring basis only. It does not include triggering corpus bytes, does not "
            "target a production app, and does not claim that the pinned target app is vulnerable. Android platform "
            "decoder and vendored-library boundaries must be resolved in the next phase."
        ),
        "provenance": provenance("phase0 ReproChain mapping scaffold"),
        "safety_flags": [],
    }
    return finalize_record(record, previous_hash=previous_hash)


def map_targets(root: Path) -> dict[str, Any]:
    previous_hash: str | None = None
    records = []
    for target_key in TARGETS:
        record = _mapping_record(target_key, previous_hash)
        previous_hash = record["hash_chain"]["record_hash"]
        records.append(record)
    manifest = {
        "tool_output_type": "reprochain_mapping",
        "version": "v1.0",
        "generated_by": "aegisgraph-tier3-research",
        "generated_at": STATIC_GENERATED_AT,
        "safety_posture": "private_by_default",
        "records": records,
    }
    write_json(root / "reprochain" / "evidence" / "mapping.json", manifest)
    return manifest
