// auto-generated by aegisgraph harnessgen (avifDecoderRead)
//
// libFuzzer entrypoint wrapping a native target function. The shape is the
// canonical Asemarefactor.md Engine 2 image-family template (lines 215-225)
// extended with the libavif decoder lifecycle: create-decoder ->
// create-image -> read-memory -> destroy-image -> destroy-decoder. Build
// with ASAN + UBSan + libfuzzer per the sibling Makefile. Run only inside
// the HarnessGen sandbox (docker, self-hosted runner) -- never on a
// developer workstation, never against a live target.
//
// The crash bytes this harness produces NEVER appear in evidence records.
// They are written into reprochain/corpora-private/ and referenced by
// SHA-256 in the AG-CRASH-* record schema (schema/crash.schema.json).

#include <cstddef>
#include <cstdint>
#include <avif/avif.h>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    avifDecoder* decoder = avifDecoderCreate();
    if (!decoder) {
        return 0;
    }
    avifImage* image = avifImageCreateEmpty();
    if (!image) {
        avifDecoderDestroy(decoder);
        return 0;
    }
    avifResult result = avifDecoderReadMemory(decoder, image, data, size);
    (void)result;
    avifImageDestroy(image);
    avifDecoderDestroy(decoder);
    return 0;
}
