// auto-generated by aegisgraph harnessgen (WebPDecodeRGB)
//
// libFuzzer entrypoint wrapping a native target function. The shape is the
// canonical Asemarefactor.md Engine 2 template (lines 215-225). Build with
// ASAN + UBSan + libfuzzer per the sibling Makefile. Run only inside the
// HarnessGen sandbox (docker, self-hosted runner) -- never on a developer
// workstation, never against a live target.
//
// The crash bytes this harness produces NEVER appear in evidence records.
// They are written into reprochain/corpora-private/ and referenced by
// SHA-256 in the AG-CRASH-* record schema (schema/crash.schema.json).

#include <cstddef>
#include <cstdint>
#include <webp/decode.h>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    int w = 0;
    int h = 0;
    uint8_t* rgb = WebPDecodeRGB(data, size, &w, &h);
    if (rgb != nullptr) {
        WebPFree(rgb);
    }
    return 0;
}
